name: CodeQuality
on:
  workflow_call:
    secrets:
      SENTRY_AUTH_TOKEN:
        required: false
      GERICHTSFINDER_ENCRYPTION_KEY:
        required: false

jobs:
  code-quality:
    strategy:
      matrix:
        cmd: ["format", "lint", "typecheck", "test:coverage", "build"]
    permissions:
      contents: read
    runs-on: ubuntu-latest
    name: pnpm run ${{ matrix.cmd }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: ./.github/actions/cached-checkout-install
      - run: pnpm run ${{ matrix.cmd }}
        env:
          SENTRY_AUTH_TOKEN: "${{ secrets.SENTRY_AUTH_TOKEN }}"
          GERICHTSFINDER_ENCRYPTION_KEY: "${{ secrets.GERICHTSFINDER_ENCRYPTION_KEY }}"
      - name: Upload coverage
        if: ${{ matrix.cmd == 'test:coverage' }}
        uses: actions/upload-artifact@v6
        with:
          name: coverage
          path: coverage/
          retention-days: 1
      - name: Upload build
        if: ${{ matrix.cmd == 'build'  && github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v6
        with:
          name: build
          path: build/
          retention-days: 1
          include-hidden-files: true
